name: Recipe Realm Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change server directory
        run: cd nodeserver
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - name: Build backend
        run: npm run build --if-present
        working-directory: ./nodeserver

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Navigate to server directory
        run: cd nodeserver
      - name: npm ins
        run: npm install
        working-directory: ./nodeserver
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}